### ISSUE TITLE
Cannot make it work with browserify transform sweetify

### ISSUE THREAD

**Issue by felix-d** [disnet/contracts.js#28]
Hey, I'm trying to use `contracts.js` with [sweetify](https://www.npmjs.com/package/sweetify) but without success. The bundle compiles but `contracts.js` code doesn't seem to be included in the bundle and when I try to add `import @ from 'contracts.js';` in the `sjs` file, a token error is reported by `sweetify`. 

But it does work with `sweet.js` cli. The problem might be with `sweetify`, but the repo doesn't seem to be maintained anymore.

Does anyone has went through the same issues trying to make this work with browserify? Thank you!

**Comment by disnet** [comment]
It looks like sweetify is using an older version of sweet.js. That might be contributing to the problem.

**Comment by felix-d** [comment]
Yeah, I did try manually updating it directly in the node modules of sweetify to the latest version but didn't have any success. Anyway, went for rho-contracts. Less sexy but suits my needs :)  Thanks!
